######################################
#
# Voltseon's Trainer Generator
#
######################################
# Version 1.1
######################################
#
# Configuration
#
######################################

# Common event that plays before the battle starts
RT_COMMON_EVENT_ID = 3

# The odds of the trainer using a gender neutral name
GENDER_NEUTRAL_CHANCE = 25 # Out of 100

# Force the pokemon to be unevolved below a certain level (to disable put 0)
FORCED_UNEVOLVED_LEVEL = 0

# Force the pokemon to be fully evolved after a certain level (to disable put 100)
FORCED_FULLY_EVOLVED_LEVEL = 100

# Whether to use the species blacklist or whitelist
# true = blacklist, false = whitelist
USE_SPECIES_BLACKLIST = true

# An array of lose texts
LOSE_TEXTS = [
  "Aww man, I thought I had a chance.",
  "I suppose I am the loser.",
  "Wow, you're pretty strong!",
  "Those were some cool moves!",
  "Pfft. Before I could get serious, I lost!",
  "OK! I give up!",
  "I lost. I lost!",
  "I'm glad I got to see your Pokemon!",
  "Hmm. This is disappointing.",
  "Ow, ow, ow!",
  "Just as I thought, you're tough!",
  "Argh, I can't do anymore...",
  "Looks like you're the stronger one...",
  "Way to go!",
  "That's too bad.",
  "Just what I expected.",
  "Oh... That's disappointing!",
  "That's odd.",
  "...Humph! Are you happy you won?",
  "Tch! I tried to rush things...",
  "Argh! You're too strong!",
  "I was not expecting to lose that hard.",
  "Aack! My Pokemon!",
  "I was no match...",
  "Didn't I train enough?",
  "I see. So you can battle that way.",
  "That's strange. I won before.",
  "I was whipped...",
  "...Hmmm...",
  "Yow! You're too strong!",
  "This can't be true!",
  "Gaah!",
  "Yikes! Not fast enough!",
  "What an amazing battle!",
  "Phew...",
  "Pretty impressive! I'm sure you can go anywhere with that skill!",
  "You're too much!",
  "Good battle!",
  "Gwa ha ha! I lost.",
  "I can't move anymore...",
  "That's shocking!",
  "Whew... Good battle.",
  "Oh, yikes! We lost!",
  "Whatever!",
  "Heh, I guess I didn't try hard enough.",
  "I lost that one!",
  "Gulp! This is a bleak moment.",
  "Mercy!",
  "Tch! I took you too lightly!",
  "Uh-oh! I was also sunk by indecision!",
  "Ayeeee!",
  "Uww... I blew it.",
  "Impresive...",
  "We give up! You're the winner!",
  "Looks like we underestimated you",
  "Oh, so close! I almost had you!",
  "...did I win?",
  "Oh... I lost... you're not weak...",
  "Oh, dear! I wanted to win!",
  "Yikes! Sorry!",
  "... ... I'll go train some more...",
  "Yaha! I lost!",
  "I was no match...",
  "Uwahauwaha!",
  "Nyuraahahhaah",
  "You never saw me...",
  "Uwaaah! Eeek!",
  "Grr! I lost that...",
  "Oh... I lost...",
  "Peace--even though I lost!",
  "I did not expect to lose this battle.",
  "Ugh, why do I always keep losing these battles?",
  "No way!",
  "Aww, darn it!",
  "You cheated! It's that simple.",
  "I should've guessed you would cheat.",
  "I thought I was prepared for anything!",
  "I can't accept defeat like this...",
  "I knew you would win.",
  "Wow, you're too good!",
  "This can't be happening.",
  "Wow! You're super impressive.",
  "Hang on, this makes no sense..."
]

WEAK_SPECIES_WHITELIST = [
:WISHIWASHI, :SUNKERN, :BLIPBUG, :SNOM, :AZURILL, :KRICKETOT, :CATERPIE, :WEEDLE, :WURMPLE, :RALTS, :MAGIKARP, :FEEBAS, :SCATTERBUG, :COSMOG, :METAPOD, :KAKUNA, :PICHU, :SILCOON, :CASCOON, :IGGLYBUFF, :WOOPER, :TYROGUE, :BOUNSWEET, :SPEWPA, :SENTRET, :CLEFFA, :POOCHYENA, :LOTAD, :SEEDOT, :HAPPINY, :BURMY, :WIMPOD, :SHEDINJA, :MAKUHITA, :BUNNELBY, :ZIGZAGOON, :WHISMUR, :ROLYCOLY, :TOXEL, :COMBEE, :ZUBAT, :TOGEPI, :STARLY, :NOIBAT, :ROOKIDEE, :NICKIT, :SPINARAK, :MARILL, :HOPPIP, :SLUGMA, :SWINUB, :SMEARGLE, :BIDOOF, :FOMANTIS, :GOSSIFLEUR, :PIDGEY, :RATTATA, :YUNGOOS, :PATRAT, :SKITTY, :WYNAUT, :VENIPEDE, :APPLIN, :SPEAROW, :HOOTHOOT, :SHINX, :PIDOVE, :DIGLETT, :LEDYBA, :PIKIPEK, :HATENNA, :IMPIDIMP, :NINCADA, :SURSKIT, :DEWPIDER, :JIGGLYPUFF, :TAILLOW, :WINGULL, :WOOLOO, :YAMPER, :MILCERY, :DREEPY, :NIDORANfE, :NIDORANmA, :CHERUBI, :LILLIPUP, :TYNAMO, :LITWICK, :SKWOVET, :KIRLIA, :FLETCHLING, :MAREEP, :SLAKOTH, :MEDITITE, :BUDEW, :ROGGENROLA, :COTTONEE, :PETILIL, :ROCKRUFF, :ARROKUDA, :PURRLOIN, :CHEWTLE, :PARAS, :CHINGLING, :RIOLU, :MORELULL, :EKANS, :DITTO, :BARBOACH, :INKAY, :HELIOPTILE, :MEOWTH, :PINECO, :TRAPINCH, :SPHEAL, :BONSLY, :GOTHITA, :SOLOSIS, :STEENEE, :MUNNA, :SANDILE, :TYMPOLE, :FOONGUS, :HORSEA, :SHROOMISH, :ELECTRIKE, :SHUPPET, :DUSKULL, :BLITZLE, :VULPIX, :SANDSHREW, :POLIWAG, :BELLSPROUT, :GEODUDE, :DRATINI, :SNUBBULL, :REMORAID, :LARVITAR, :BALTOY, :SNORUNT, :BAGON, :BELDUM, :BRONZOR, :GIBLE, :CROAGUNK, :MINCCINO, :KLINK, :DEINO, :GOOMY, :GRUBBIN, :JANGMOO, :MELTAN, :GULPIN, :YAMASK, :GOLETT, :FLABÉBÉ, :BERGMITE, :CUTIEFLY, :VENONAT, :MANKEY, :MACHOP, :SHELLDER, :SMOOCHUM, :CARVANHA, :NUMEL, :TIMBURR, :DUCKLETT, :VANILLITE, :FERROSEED, :CUBCHOO, :SHELMET, :MAREANIE, :SIZZLIPEDE, :BINACLE, :FENNEKIN, :CORPHISH, :SNIVY, :TEPIG, :OSHAWOTT, :SINISTEA, :CHARMANDER, :CYNDAQUIL, :CHIMCHAR, :PHANTUMP, :ABRA, :DODUO, :GASTLY, :TREECKO, :TORCHIC, :MUDKIP, :SWABLU, :GLAMEOW, :MIMEJR, :SEWADDLE, :GROOKEY, :SCORBUNNY, :SOBBLE, :CLOBBOPUS, :CHESPIN, :SQUIRTLE, :TOTODILE, :PIPLUP, :FROAKIE, :SLOWPOKE, :DARUMAKA, :KARRABLAST, :SILICOBRA, :PANSAGE, :PANSEAR, :PANPOUR, :BULBASAUR, :CHIKORITA, :TURTWIG, :JOLTIK, :PIKACHU, :ODDISH, :PSYDUCK, :CUBONE, :GOLDEEN, :NATU, :AXEW, :SKRELP, :ROWLET, :LITTEN, :POPPLIO, :SALANDIT, :SANDYGAST, :CLEFAIRY, :WOOBAT, :MAGNEMITE, :SEEL, :GRIMER, :KRABBY, :EXEGGCUTE, :EEVEE, :SHELLOS, :DWEBBLE, :HONEDGE, :DROWZEE, :DRILBUR, :STUNKY, :TRUBBISH, :VOLTORB, :CHINCHOU, :TEDDIURSA, :DELIBIRD, :HOUNDOUR, :PHANPY, :ARON, :SPOINK, :LUVDISC, :BUIZEL, :HIPPOPOTAS, :SKORUPI, :FINNEON, :ZORUA, :CLAUNCHER, :CUFANT, :SNOVER, :TENTACOOL, :CACNEA, :DEERLING, :FRILLISH, :ELGYEM, :PUMPKABOO, :DOTTLER, :UNOWN, :CRABRAWLER, :KOFFING, :STARYU, :SKIPLOOM, :LOMBRE, :NUZLEAF, :VIBRAVA, :STARAVIA, :PAWNIARD, :STUFFUL, :SPRITZEE, :SWIRLIX, :RHYHORN, :CLAMPERL, :MANTYKE, :DRIFLOON, :SCRAGGY, :PANCHAM, :PIDGEOTTO, :GROWLITHE, :CRANIDOS, :SHIELDON, :BUNEARY, :MIENFOO, :RUFFLET, :SKIDDO, :KROKOROK, :OMANYTE, :KABUTO, :LILEEP, :ANORITH, :TIRTOUGA, :ESPURR, :TRUMBEAK, :TRANQUILL, :AIPOM, :ELEKID, :LOUDRED, :SPINDA, :WHIRLIPEDE, :LARVESTA, :TYRUNT, :AMAURA, :LUXIO, :NIDORINA, :NIDORINO, :FLAAFFY, :MAGBY, :CORVISQUIRE
]

MODERATE_SPECIES_WHITELIST = [
:LITLEO, :HERDIER, :DUOSION, :LAMPENT, :VULLABY, :HATTREM, :MORGREM, :FLOETTE, :NOSEPASS, :FARFETCHD, :SABLEYE, :MAWILE, :SWADLOON, :FLETCHINDER, :KRICKETUNE, :PALPITOAD, :POLIWHIRL, :ONIX, :LICKITUNG, :DUSTOX, :MUDBRAY, :KUBFU, :WEEPINBELL, :GRAVELER, :LEDIAN, :YANMA, :MUNCHLAX, :BOLDORE, :GOTHORITA, :BUTTERFREE, :BEEDRILL, :GLOOM, :PORYGON, :BEAUTIFLY, :VANILLISH, :KADABRA, :ARIADOS, :DELCATTY, :ROSELIA, :WAILMER, :CHARJABUG, :COSMOEM, :ARCHEN, :IVYSAUR, :CHARMELEON, :WARTORTLE, :PARASECT, :MACHOKE, :HAUNTER, :BAYLEEF, :QUILAVA, :CROCONAW, :TOGETIC, :MURKROW, :WOBBUFFET, :GROVYLE, :COMBUSKEN, :MARSHTOMP, :PLUSLE, :MINUN, :GROTLE, :MONFERNO, :PRINPLUP, :PACHIRISU, :GURDURR, :EELEKTRIK, :QUILLADIN, :FROGADIER, :SHIINOTIC, :BRAIXEN, :PONYTA, :SUDOWOODO, :CORSOLA, :PUPITAR, :MEDICHAM, :SEALEO, :BIBAREL, :GABITE, :FRAXURE, :PYUKUMUKU, :CARKOL, :DRAKLOAK, :CHATOT, :VIVILLON, :RATICATE, :SERVINE, :DEWOTT, :FURRET, :DUNSPARCE, :PIGNITE, :GUMSHOOS, :DRAGONAIR, :AZUMARILL, :MIGHTYENA, :LINOONE, :CASTFORM, :SHELGON, :METANG, :WATCHOG, :ZWEILOUS, :DARTRIX, :TORRACAT, :BRIONNE, :HAKAMOO, :POIPOLE, :THWACKEY, :RABOOT, :DRIZZILE, :DIGGERSBY, :WORMADAM, :MOTHIM, :DUGTRIO, :MAROWAK, :SUNFLORA, :SWOOBAT, :EMOLGA, :QUAGSIRE, :GLIGAR, :SNEASEL, :MAGCARGO, :LAIRON, :VOLBEAT, :ILLUMISE, :DEDENNE, :WIGGLYTUFF, :TANGELA, :MISDREAVUS, :TOGEDEMARU, :PINCURCHIN, :MORPEKO, :PERSIAN, :SEADRA, :QWILFISH, :PELIPPER, :VIGOROTH, :KECLEON, :ROTOM, :KLANG, :MINIOR, :PERRSERKER, :FEAROW, :AUDINO, :LIEPARD, :ARBOK, :DOUBLADE, :SANDSLASH, :VENOMOTH, :CHANSEY, :SEAKING, :GRANBULL, :PILOSWINE, :CHERRIM, :NOCTOWL, :PURUGLY, :SLIGGOO, :MASQUERAIN, :CARNIVINE, :ARAQUANID, :GOLBAT, :PRIMEAPE, :HITMONLEE, :HITMONCHAN, :JYNX, :GIRAFARIG, :HITMONTOP, :SWELLOW, :BANETTE, :DUSCLOPS, :CHIMECHO, :THIEVUL, :NINJASK, :ZANGOOSE, :SEVIPER, :MRMIME, :LANTURN, :JUMPLUFF, :BRELOOM, :SHARPEDO, :CAMERUPT, :LUNATONE, :SOLROCK, :TROPIUS, :LUMINEON, :BASCULIN, :GREEDENT, :ELDEGOSS, :MARACTUS, :AROMATISSE, :AMOONGUSS, :RIBOMBEE, :MAGNETON, :FORRETRESS, :SKARMORY, :STANTLER, :ABSOL, :THROH, :SAWK, :MEOWSTIC, :SWALOT, :WHISCASH, :CRAWDAUNT
]

STRONG_SPECIES_WHITELIST = [
:DODRIO, :XATU, :TORKOAL, :GRUMPIG, :CINCCINO, :ALOMOMOLA, :KLEFKI, :FALINKS, :STONJOURNER, :EISCUE, :STUNFISK, :GALVANTULA, :FURFROU, :SWANNA, :HARIYAMA, :VESPIQUEN, :GARBODOR, :TREVENANT, :DEWGONG, :KINGLER, :MANECTRIC, :CACTURNE, :GASTRODON, :SAWSBUCK, :BRUXISH, :CRAMORANT, :FROSMOTH, :INDEEDEE, :ORICORIO, :MIMIKYU, :CRABOMINABLE, :PIDGEOT, :SKUNTANK, :OCTILLERY, :LUDICOLO, :SHIFTRY, :GLALIE, :LOPUNNY, :FROSLASS, :PHIONE, :WHIMSICOTT, :LILLIGANT, :DARMANITAN, :JELLICENT, :SLURPUFF, :LURANTIS, :SALAZZLE, :PALOSSAND, :KOMALA, :GRAPPLOCT, :HELIOLISK, :AMBIPOM, :MALAMAR, :CLEFABLE, :HYPNO, :COFAGRIGUS, :GOLURK, :RUNERIGUS, :HEATMOR, :DURANT, :RAICHU, :RHYDON, :MANTINE, :HUNTAIL, :GOREBYSS, :RELICANTH, :STARAPTOR, :SPIRITOMB, :SCOLIPEDE, :CRUSTLE, :BEHEEYEM, :DRUDDIGON, :TOUCANNON, :COMFEY, :TURTONATOR, :DRAMPA, :DREDNAW, :FLAPPLE, :APPLETUN, :MUSHARNA, :LYCANROC, :UNFEZANT, :SCRAFTY, :FERROTHORN, :VILEPLUME, :VICTREEBEL, :SLOWBRO, :ELECTRODE, :WEEZING, :KANGASKHAN, :ELECTABUZZ, :TAUROS, :BELLOSSOM, :SLOWKING, :MILTANK, :EXPLOUD, :ALTARIA, :TOXICROAK, :SIGILYPH, :GOTHITELLE, :REUNICLUS, :BISHARP, :BOUFFALANT, :ORANGURU, :PASSIMIAN, :DUBWOOL, :BOLTUND, :BARRASKEWDA, :ABOMASNOW, :DRAGALGE, :GOURGEIST, :GOLEM, :MAGMAR, :OMASTAR, :KABUTOPS, :CRADILY, :ARMALDO, :RAMPARDOS, :BASTIODON, :FLOATZEL, :MISMAGIUS, :CARRACOSTA, :ESCAVALIER, :ACCELGOR, :PANGORO, :TOXAPEX, :CORVIKNIGHT, :ALCREMIE, :ZEBSTRIKA, :DRIFBLIM, :SIMISAGE, :SIMISEAR, :SIMIPOUR, :TALONFLAME, :GOLDUCK, :ALAKAZAM, :RAPIDASH, :MUK, :GENGAR, :SCYTHER, :PINSIR, :POLITOED, :SCIZOR, :HERACROSS, :URSARING, :HOUNDOOM, :DONPHAN, :WAILORD, :CLAYDOL, :BRONZONG, :DRAPION, :STOUTLAND, :LEAVANNY, :AEGISLASH, :BARBARACLE, :CLAWITZER, :HAWLUCHA, :CARBINK, :VIKAVOLT, :MUDSDALE, :BEWEAR, :COPPERAJAH, :CALYREX, :TOXTRICITY, :NIDOQUEEN, :NIDOKING, :NINETALES, :MACHAMP, :SHUCKLE, :HONCHKROW, :CONKELDURR, :BEARTIC, :ORBEETLE, :DRACOZOLT, :ARCTOZOLT, :DRACOVISH, :ARCTOVISH, :PYROAR, :SIRFETCHD, :EXCADRILL, :POLTEAGEIST, :SEISMITOAD, :POLIWRATH, :AMPHAROS, :STEELIX, :WEAVILE, :GLISCOR, :ZOROARK, :MIENSHAO, :BRAVIARY, :MANDIBUZZ, :TSAREENA, :COALOSSAL, :SANDACONDA, :HATTERENE, :GRIMMSNARL, :CURSOLA, :AVALUGG, :TENTACRUEL, :AERODACTYL, :PORYGON2, :ROSERADE, :LICKILICKY, :YANMEGA, :GIGALITH, :EELEKTROSS, :CRYOGONAL, :DHELMISE, :GARDEVOIR, :GALLADE, :KROOKODILE, :STARMIE, :FLYGON, :KLINKLANG, :CHANDELURE, :OBSTAGOON, :MRRIME, :TYRANTRUM, :AURORUS, :LUXRAY, :VENUSAUR, :CLOYSTER, :VAPOREON, :JOLTEON, :FLAREON, :MEGANIUM, :ESPEON, :UMBREON, :TORTERRA, :LUCARIO, :HIPPOWDON, :LEAFEON, :GLACEON, :PROBOPASS, :DUSKNOIR, :SYLVEON, :CENTISKORCH, :SERPERIOR, :EMBOAR, :SAMUROTT, :BLASTOISE, :EXEGGUTOR, :FERALIGATR, :SCEPTILE, :BLAZIKEN, :AGGRON, :WALREIN, :EMPOLEON, :MAMOSWINE, :CHESNAUGHT, :GRENINJA, :DECIDUEYE, :INCINEROAR, :PRIMARINA, :GOLISOPOD, :RILLABOOM, :CINDERACE, :INTELEON, :GOGOAT, :CHARIZARD, :TYPHLOSION, :INFERNAPE, :DELPHOX, :LAPRAS, :CROBAT, :SWAMPERT, :MAGNEZONE, :RHYPERIOR, :TANGROWTH, :PORYGONZ, :VANILLUXE, :NOIVERN, :DURALUDON, :GYARADOS, :SNORLAX, :KINGDRA, :BLISSEY, :MILOTIC, :ELECTIVIRE, :MAGMORTAR, :HAXORUS, :NAGANADEL, :TOGEKISS, :VOLCARONA, :URSHIFU, :FLORGES, :ARCANINE, :ARCHEOPS
]

LEGENDARY_SPECIES_WHITELIST = [
:SILVALLY, :TAPUKOKO, :TAPULELE, :TAPUBULU, :TAPUFINI, :NIHILEGO, :BUZZWOLE, :PHEROMOSA, :XURKITREE, :CELESTEELA, :KARTANA, :GUZZLORD, :STAKATAKA, :BLACEPHALON, :ARTICUNO, :ZAPDOS, :MOLTRES, :RAIKOU, :ENTEI, :SUICUNE, :REGIROCK, :REGICE, :REGISTEEL, :UXIE, :MESPRIT, :AZELF, :COBALION, :TERRAKION, :VIRIZION, :TORNADUS, :THUNDURUS, :KELDEO, :REGIELEKI, :REGIDRAGO, :GLASTRIER, :SPECTRIER, :DRAGONITE, :MEW, :TYRANITAR, :CELEBI, :SALAMENCE, :METAGROSS, :LATIAS, :LATIOS, :JIRACHI, :DEOXYS, :GARCHOMP, :HEATRAN, :CRESSELIA, :MANAPHY, :DARKRAI, :SHAYMIN, :VICTINI, :HYDREIGON, :LANDORUS, :MELOETTA, :GENESECT, :GOODRA, :ZYGARDE, :DIANCIE, :HOOPA, :VOLCANION, :KOMMOO, :NECROZMA, :MAGEARNA, :MARSHADOW, :ZERAORA, :MELMETAL, :DRAGAPULT, :ZARUDE, :KYUREM, :SLAKING, :KYOGRE, :GROUDON, :REGIGIGAS, :ZACIAN, :ZAMAZENTA, :MEWTWO, :LUGIA, :HOOH, :RAYQUAZA, :DIALGA, :PALKIA, :GIRATINA, :RESHIRAM, :ZEKROM, :XERNEAS, :YVELTAL, :SOLGALEO, :LUNALA, :ETERNATUS, :ARCEUS
]

# An array of available Pokémon
SPECIES_WHITELIST = [
  :BULBASAUR, :IVYSAUR, :VENUSAUR,
  :CHARMANDER, :CHARMELEON, :CHARIZARD,
  :SQUIRTLE, :WARTORTLE, :BLASTOISE,
  :CATERPIE, :METAPOD, :BUTTERFREE,
  :WEEDLE, :KAKUNA, :BEEDRILL,
  :PIDGEY, :PIDGEOTTO, :PIDGEOT,
  :RATTATA, :RATICATE,
  :SPEAROW, :FEAROW,
  :EKANS, :ARBOK,
  :PIKACHU, :RAICHU,
  :SANDSHREW, :SANDSLASH,
  :NIDORANfE, :NIDORINA, :NIDOQUEEN,
  :NIDORANmA, :NIDORINO, :NIDOKING,
  :CLEFAIRY, :CLEFABLE,
  :VULPIX, :NINETALES,
  :JIGGLYPUFF, :WIGGLYTUFF,
  :ZUBAT, :GOLBAT,
  :ODDISH, :GLOOM, :VILEPLUME,
  :PARAS, :PARASECT,
  :VENONAT, :VENOMOTH,
  :DIGLETT, :DUGTRIO,
  :MEOWTH, :PERSIAN,
  :PSYDUCK, :GOLDUCK,
  :MANKEY, :PRIMEAPE,
  :GROWLITHE, :ARCANINE,
  :POLIWAG, :POLIWHIRL, :POLIWRATH,
  :ABRA, :KADABRA, :ALAKAZAM,
  :MACHOP, :MACHOKE, :MACHAMP,
  :BELLSPROUT, :WEEPINBELL, :VICTREEBEL,
  :TENTACOOL, :TENTACRUEL,
  :GEODUDE, :GRAVELER, :GOLEM,
  :PONYTA, :RAPIDASH,
  :SLOWPOKE, :SLOWBRO,
  :MAGNEMITE, :MAGNETON,
  :FARFETCHD,
  :DODUO, :DODRIO,
  :SEEL, :DEWGONG,
  :GRIMER, :MUK,
  :SHELLDER, :CLOYSTER,
  :GASTLY, :HAUNTER, :GENGAR,
  :ONIX,
  :DROWZEE, :HYPNO,
  :KRABBY, :KINGLER,
  :VOLTORB, :ELECTRODE,
  :EXEGGCUTE, :EXEGGUTOR,
  :CUBONE, :MAROWAK,
  :HITMONLEE, :HITMONCHAN,
  :LICKITUNG,
  :KOFFING, :WEEZING,
  :RHYHORN, :RHYDON,
  :CHANSEY,
  :TANGELA,
  :KANGASKHAN,
  :HORSEA, :SEADRA,
  :GOLDEEN, :SEAKING,
  :STARYU, :STARMIE,
  :MRMIME,
  :SCYTHER,
  :JYNX,
  :ELECTABUZZ,
  :MAGMAR,
  :PINSIR,
  :TAUROS,
  :MAGIKARP, :GYARADOS,
  :LAPRAS,
  :DITTO,
  :EEVEE, :VAPOREON, :JOLTEON, :FLAREON,
  :PORYGON,
  :OMANYTE, :OMASTAR,
  :KABUTO, :KABUTOPS,
  :AERODACTYL,
  :DRATINI, :DRAGONAIR, :DRAGONITE
]

# An array of banned Pokémon
SPECIES_BLACKLIST = [
  :ZAPDOS, :MOLTRES, :ARTICUNO,
  :MEW, :MEWTWO,
  :RAIKOU, :SUICUNE, :ENTEI,
  :LUGIA, :CELEBI, :HOOH,
  :LATIAS, :LATIOS,
  :REGICE, :REGISTEEL, :REGIROCK,
  :GROUDON, :KYOGRE, :RAYQUAZA,
  :JIRACHI,
  :DEOXYS, :DEOXYS_1, :DEOXYS_2, :DEOXYS_3,
  :UXIE, :MESPRIT, :AZELF,
  :HEATRAN,
  :DIALGA, :PALKIA,
  :GIRATINA, :GIRATINA_1,
  :REGIGIGAS,
  :CRESSELIA, :DARKRAI,
  :SHAYMIN, :SHAYMIN_1,
  :MANAPHY, :PHIONE,
  :VICTINI,
  :RESHIRAM, :ZEKROM,
  :KYUREM, :KYUREM_1, :KYUREM_2,
  :TORNADUS, :THUNDURUS, :LANDORUS,
  :TORNADUS_1, :THUNDURUS_1, :LANDORUS_1,
  :COBALION, :TERRAKION, :VIRIZION,
  :KELDEO, :MELOETTA,
  :KELDEO_1, :MELOETTA_1,
  :GENESECT, :GENESECT_1, :GENESECT_2, :GENESECT_3, :GENESECT_4,
  :XERNEAS, :YVELTAL, :ZYGARDE,
  :DIANCIE, :HOOPA, :HOOPA_1, :VOLCANION,
  :TAPUKOKO, :TAPULELE, :TAPUBULU, :TAPUFINI,
  :COSMOG, :COSMOEM, :SOLGALEO, :LUNALA,
  :MAGEARNA, :MARSHADOW,
  :ZERAORA,
  :MELTAN, :MELMETAL,
  :NIHILEGO, :BUZZWOLE, :PHEROMOSA,
  :XURKITREE, :CELESTEELA, :KARTANA,
  :GUZZLORD,
  :POIPOLE, :NAGANADEL,
  :STAKATAKA, :BLACEPHALON
]

# An array of possible Items
ITEM_WHITELIST = [
  :HYPERPOTION,
  :MAXPOTION,
  :FULLRESTORE,
  :XATTACK,
  :XDEFENSE,
  :XSPATK,
  :XSPDEF,
  :XSPEED,
  :XACCURACY,
  :DIREHIT,
  :FULLHEAL
]

# An array of all viable trainer classes
# [CLASS, Overworld, Preferred types / species]
RT_TRAINER_WHITELIST = [
  [:AROMALADY,"trainer_AROMALADY",:GRASS,:FAIRY],
  [:BEAUTY,"trainer_BEAUTY",:NORMAL],
  [:BIKER,"trainer_BIKER",:NORMAL,:ELECTRIC,:FLYING],
  [:BIRDKEEPER,"trainer_BIRDKEEPER",:FLYING],
  [:BUGCATCHER,"trainer_BUGCATCHER",:BUG],
  [:BURGLAR,"trainer_BURGLAR",:DARK,:NORMAL],
  [:CHANELLER,"trainer_CHANELLER",:GHOST,:PSYCHIC],
  [:CUEBALL,"trainer_CUEBALL",:STEEL,:NORMAL],
  [:ENGINEER,"trainer_ENGINEER",:ELECTRIC,:STEEL],
  [:FISHERMAN,"trainer_FISHERMAN",:WATER],
  [:GAMBLER,"trainer_GAMBLER"],
  [:GENTLEMAN,"trainer_GENTLEMAN",:NORMAL],
  [:HIKER,"trainer_HIKER",:ROCK,:GROUND],
  [:JUGGLER,"trainer_JUGGLER"],
  [:LADY,"trainer_LADY",:NORMAL],
  [:PAINTER,"trainer_PAINTER",:NORMAL,:FAIRY],
  [:POKEMANIAC,"trainer_POKEMANIAC",:NORMAL,:ELECTRIC,:GROUND],
  [:POKEMONBREEDER,"trainer_POKEMONBREEDER",:PICHU,:TOGEPI,:IGGLYBUFF,:CLEFFA,:RIOLU,:CHINGLING,:TYROGUE,:SMOOCHUM,
    :ELEKID,:MAGBY,:AZURILL,:WYNAUT,:BUDEW,:BONSLY,:MIMEJR,:HAPPINY,:MUNCHLAX,:MANTYKE],
  [:ROCKER,"trainer_ROCKER",:ELECTRIC],
  [:RUINMANIAC,"trainer_RUINMANIAC",:ROCK,:KABUTO,:KABUTOPS,:OMANYTE,:OMASTAR,:AERODACTYL,:LILEEP,:CRADILY,:ANORITH,
    :ARMALDO,:RELICANTH,:CRANDIOS,:RAMPARDOS,:SHIELDON,:BASTIODON,:TIRTOUGA,:CARRACOSTA,:ARCHEN,:ARCHEOPS],
  [:SAILOR,"trainer_SAILOR",:WATER],
  [:SCIENTIST,"trainer_SCIENTIST",:ELECTRIC,:STEEL],
  [:SUPERNERD,"trainer_SUPERNERD",:ELECTRIC,:STEEL],
  [:TAMER,"trainer_TAMER",:DRAGON],
  [:BLACKBELT,"trainer_BLACKBELT",:FIGHTING],
  [:CRUSHGIRL,"trainer_CRUSHGIRL",:FIGHTING],
  [:CAMPER,"trainer_CAMPER",:NORMAL,:FAIRY,:GRASS,:ELECTRIC,:GROUND],
  [:PICNICKER,"trainer_PICNICKER",:NORMAL,:FAIRY,:GRASS,:ELECTRIC,:GROUND],
  [:COOLTRAINER_M,"trainer_COOLTRAINER_M"],
  [:COOLTRAINER_F,"trainer_COOLTRAINER_F"],
  [:YOUNGSTER,"trainer_YOUNGSTER",:NORMAL],
  [:LASS,"trainer_LASS",:NORMAL],
  [:POKEMONRANGER_M,"trainer_POKEMONRANGER_M"],
  [:POKEMONRANGER_F,"trainer_POKEMONRANGER_F"],
  [:PSYCHIC_M,"trainer_PSYCHIC_M",:PSYCHIC],
  [:PSYCHIC_F,"trainer_PSYCHIC_F",:PSYCHIC],
  [:SWIMMER_M,"trainer_SWIMMER_M",:WATER],
  [:SWIMMER_F,"trainer_SWIMMER_F",:WATER],
  [:SWIMMER2_M,"trainer_SWIMMER2_M",:WATER],
  [:SWIMMER2_F,"trainer_SWIMMER2_F",:WATER],
  [:TUBER_M,"trainer_TUBER_M",:WATER],
  [:TUBER_F,"trainer_TUBER_F",:WATER],
  [:TUBER2_M,"trainer_TUBER2_M",:WATER],
  [:TUBER2_F,"trainer_TUBER2_F",:WATER]
]